services:
  openflare-agent:
    build:
        context: .
        dockerfile: openflare_agent/Dockerfile
    container_name: openflare-agent
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:18081:18081"

    volumes:
      - ./openflare_agent/data/:/data

    environment:
      OPENFLARE_SERVER_URL: "http://host.docker.internal:3000"
      OPENFLARE_AGENT_TOKEN: "07800f31d3f181e65d18dca1407d821c"
      LOG_LEVEL: "debug"

    extra_hosts:
      - "host.docker.internal:host-gateway"