-- +goose Up
CREATE TABLE IF NOT EXISTS of_options (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL DEFAULT ''
);

INSERT OR IGNORE INTO of_options (key, value) VALUES
    ('PasswordLoginEnabled', 'true'),
    ('CapLoginEnabled', 'true'),
    ('PasswordRegisterEnabled', 'false'),
    ('EmailVerificationEnabled', 'false'),
    ('GitHubOAuthEnabled', 'false'),
    ('WeChatAuthEnabled', 'false'),
    ('SMTPPort', '587'),
    ('SystemName', 'OpenFlare'),
    ('AgentHeartbeatInterval', '10000'),
    ('AgentWebsocketUpgradeEnabled', 'true'),
    ('NodeOfflineThreshold', '120000'),
    ('AgentUpdateRepo', 'Rain-kl/OpenFlare'),
    ('GeoIPProvider', 'ipinfo'),
    ('DatabaseAutoCleanupEnabled', 'false'),
    ('DatabaseAutoCleanupRetentionDays', '30'),
    ('UptimeKumaEnabled', 'false'),
    ('UptimeKumaMonitorScope', 'all'),
    ('UptimeKumaSyncInterval', '5'),
    ('UptimeKumaInterval', '60'),
    ('UptimeKumaRetry', '0'),
    ('UptimeKumaRetryInterval', '60'),
    ('UptimeKumaTimeout', '48'),
    ('OpenRestyDefaultServerReturnStatus', '421'),
    ('OpenRestyWorkerProcesses', 'auto'),
    ('OpenRestyWorkerConnections', '4096'),
    ('OpenRestyWorkerRlimitNofile', '65535'),
    ('OpenRestyEventsUse', 'epoll'),
    ('OpenRestyEventsMultiAcceptEnabled', 'true'),
    ('OpenRestyKeepaliveTimeout', '20'),
    ('OpenRestyKeepaliveRequests', '1000'),
    ('OpenRestyClientHeaderTimeout', '15'),
    ('OpenRestyClientBodyTimeout', '15'),
    ('OpenRestyClientMaxBodySize', '64m'),
    ('OpenRestyLargeClientHeaderBuffers', '4 16k'),
    ('OpenRestySendTimeout', '30'),
    ('OpenRestyProxyConnectTimeout', '3'),
    ('OpenRestyProxySendTimeout', '60'),
    ('OpenRestyProxyReadTimeout', '60'),
    ('OpenRestyWebsocketEnabled', 'true'),
    ('OpenRestyHTTP3Enabled', 'true'),
    ('OpenRestyProxyRequestBufferingEnabled', 'false'),
    ('OpenRestyProxyBufferingEnabled', 'true'),
    ('OpenRestyProxyBuffers', '16 16k'),
    ('OpenRestyProxyBufferSize', '8k'),
    ('OpenRestyProxyBusyBuffersSize', '64k'),
    ('OpenRestyGzipEnabled', 'true'),
    ('OpenRestyGzipMinLength', '1024'),
    ('OpenRestyGzipCompLevel', '5'),
    ('OpenRestyCacheEnabled', 'false'),
    ('OpenRestyCacheLevels', '1:2'),
    ('OpenRestyCacheInactive', '30m'),
    ('OpenRestyCacheMaxSize', '1g'),
    ('OpenRestyCacheKeyTemplate', '$scheme$host$request_uri'),
    ('OpenRestyCacheLockEnabled', 'true'),
    ('OpenRestyCacheLockTimeout', '5s'),
    ('OpenRestyCacheUseStale', 'error timeout updating http_500 http_502 http_503 http_504');

-- +goose Down
DROP TABLE IF EXISTS of_options;