package openresty

const (
	CertDirPlaceholder             = "__OPENFLARE_CERT_DIR__"
	RouteConfigPlaceholder         = "__OPENFLARE_ROUTE_CONFIG__"
	AccessLogPlaceholder           = "__OPENFLARE_ACCESS_LOG__"
	LuaDirPlaceholder              = "__OPENFLARE_LUA_DIR__"
	ObservabilityListenPlaceholder = "__OPENFLARE_OBSERVABILITY_LISTEN__"
	ObservabilityPortPlaceholder   = "__OPENFLARE_OBSERVABILITY_PORT__"
	PowStaticDirPlaceholder        = "__OPENFLARE_POW_STATIC_DIR__"

	SourceConfigFileName = "openresty_source_config.json"
)

const (
	cachePolicySuffix     = "suffix"
	cachePolicyPathPrefix = "path_prefix"
	cachePolicyPathExact  = "path_exact"
	defaultWAFBlockStatus = 418
	anubisStaticPrefix    = "/.within.website/x/cmd/anubis/static/"
	anubisAPIPrefix       = "/.within.website/x/cmd/anubis/api/"
)

const defaultMainConfigTemplate = `# This file is generated by OpenFlare. Do not edit manually.
worker_processes {{OpenRestyWorkerProcesses}};
worker_rlimit_nofile {{OpenRestyWorkerRlimitNofile}};
pid logs/nginx.pid;

events {
    worker_connections {{OpenRestyWorkerConnections}};
{{OpenRestyEventsUseDirective}}{{OpenRestyEventsMultiAcceptDirective}}}

http {
    include       mime.types;
    default_type  application/octet-stream;
{{OpenRestyConnectionUpgradeMap}}{{OpenRestyDefaultServerBlock}}    log_format openflare_json escape=json '{"ts":"$time_iso8601","host":"$host","path":"$request_uri","remote_addr":"$remote_addr","status":$status,"request_time":$request_time,"bytes_sent":$body_bytes_sent,"request_length":$request_length}';
    access_log {{OpenRestyAccessLogPath}} openflare_json;
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout {{OpenRestyKeepaliveTimeout}};
    keepalive_requests {{OpenRestyKeepaliveRequests}};
    client_header_timeout {{OpenRestyClientHeaderTimeout}};
    client_body_timeout {{OpenRestyClientBodyTimeout}};
    client_max_body_size {{OpenRestyClientMaxBodySize}};
    large_client_header_buffers {{OpenRestyLargeClientHeaderBuffers}};
    send_timeout {{OpenRestySendTimeout}};
    proxy_connect_timeout {{OpenRestyProxyConnectTimeout}};
    proxy_send_timeout {{OpenRestyProxySendTimeout}};
    proxy_read_timeout {{OpenRestyProxyReadTimeout}};
    proxy_request_buffering {{OpenRestyProxyRequestBuffering}};
    proxy_buffering {{OpenRestyProxyBuffering}};
    proxy_buffers {{OpenRestyProxyBuffers}};
    proxy_buffer_size {{OpenRestyProxyBufferSize}};
    proxy_busy_buffers_size {{OpenRestyProxyBusyBuffersSize}};
    gzip {{OpenRestyGzip}};
    gzip_min_length {{OpenRestyGzipMinLength}};
    gzip_comp_level {{OpenRestyGzipCompLevel}};
{{OpenRestyResolverDirective}}{{OpenRestyCacheBlock}}    include {{OpenRestyRouteConfigInclude}};
}
`

type SupportFile struct {
	Path    string `json:"path"`
	Content string `json:"content"`
}

type CustomHeader struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type PoWListConfig struct {
	IPs         []string `json:"ips"`
	IPCidrs     []string `json:"ip_cidrs"`
	Paths       []string `json:"paths"`
	PathRegexes []string `json:"path_regexes"`
	UserAgents  []string `json:"user_agents"`
}

type PoWConfig struct {
	Difficulty   int           `json:"difficulty"`
	Algorithm    string        `json:"algorithm"`
	SessionTTL   int           `json:"session_ttl"`
	ChallengeTTL int           `json:"challenge_ttl"`
	Whitelist    PoWListConfig `json:"whitelist"`
	Blacklist    PoWListConfig `json:"blacklist"`
}

type Route struct {
	ID                 uint           `json:"id,omitempty"`
	SiteName           string         `json:"site_name,omitempty"`
	Domain             string         `json:"domain"`
	Domains            []string       `json:"domains,omitempty"`
	OriginURL          string         `json:"origin_url"`
	OriginHost         string         `json:"origin_host,omitempty"`
	Upstreams          []string       `json:"upstreams,omitempty"`
	Enabled            bool           `json:"enabled"`
	EnableHTTPS        bool           `json:"enable_https"`
	CertID             *uint          `json:"cert_id,omitempty"`
	CertIDs            []uint         `json:"cert_ids,omitempty"`
	DomainCertIDs      []uint         `json:"domain_cert_ids,omitempty"`
	RedirectHTTP       bool           `json:"redirect_http"`
	LimitConnPerServer int            `json:"limit_conn_per_server,omitempty"`
	LimitConnPerIP     int            `json:"limit_conn_per_ip,omitempty"`
	LimitRate          string         `json:"limit_rate,omitempty"`
	CacheEnabled       bool           `json:"cache_enabled"`
	CachePolicy        string         `json:"cache_policy,omitempty"`
	CacheRules         []string       `json:"cache_rules,omitempty"`
	CustomHeaders      []CustomHeader `json:"custom_headers,omitempty"`
	PoWEnabled         bool           `json:"pow_enabled,omitempty"`
	PoWConfig          *PoWConfig     `json:"pow_config,omitempty"`
	BasicAuthEnabled   bool           `json:"basic_auth_enabled,omitempty"`
	BasicAuthUsername  string         `json:"basic_auth_username,omitempty"`
	BasicAuthPassword  string         `json:"basic_auth_password,omitempty"`
	Remark             string         `json:"remark,omitempty"`
}

type WAFRuleGroup struct {
	ID                uint       `json:"id"`
	Name              string     `json:"name"`
	Enabled           bool       `json:"enabled"`
	IsGlobal          bool       `json:"is_global"`
	BlockStatusCode   int        `json:"block_status_code"`
	BlockResponseBody string     `json:"block_response_body,omitempty"`
	IPWhitelist       []string   `json:"ip_whitelist,omitempty"`
	IPBlacklist       []string   `json:"ip_blacklist,omitempty"`
	CountryWhitelist  []string   `json:"country_whitelist,omitempty"`
	CountryBlacklist  []string   `json:"country_blacklist,omitempty"`
	RegionWhitelist   []string   `json:"region_whitelist,omitempty"`
	RegionBlacklist   []string   `json:"region_blacklist,omitempty"`
	PoWEnabled        bool       `json:"pow_enabled,omitempty"`
	PoWConfig         *PoWConfig `json:"pow_config,omitempty"`
}

type WAFBinding struct {
	RouteID      uint   `json:"route_id"`
	SiteName     string `json:"site_name"`
	RuleGroupIDs []uint `json:"rule_group_ids"`
}

type WAFDocument struct {
	RuleGroups []WAFRuleGroup `json:"rule_groups"`
	Bindings   []WAFBinding   `json:"bindings"`
}

type ConfigSnapshot struct {
	WorkerProcesses          string `json:"worker_processes"`
	WorkerConnections        int    `json:"worker_connections"`
	WorkerRlimitNofile       int    `json:"worker_rlimit_nofile"`
	EventsUse                string `json:"events_use,omitempty"`
	EventsMultiAcceptEnabled bool   `json:"events_multi_accept_enabled"`
	KeepaliveTimeout         int    `json:"keepalive_timeout"`
	KeepaliveRequests        int    `json:"keepalive_requests"`
	ClientHeaderTimeout      int    `json:"client_header_timeout"`
	ClientBodyTimeout        int    `json:"client_body_timeout"`
	ClientMaxBodySize        string `json:"client_max_body_size"`
	LargeClientHeaderBuffers string `json:"large_client_header_buffers"`
	SendTimeout              int    `json:"send_timeout"`
	ProxyConnectTimeout      int    `json:"proxy_connect_timeout"`
	ProxySendTimeout         int    `json:"proxy_send_timeout"`
	ProxyReadTimeout         int    `json:"proxy_read_timeout"`
	WebsocketEnabled         bool   `json:"websocket_enabled"`
	ProxyRequestBuffering    bool   `json:"proxy_request_buffering"`
	ProxyBufferingEnabled    bool   `json:"proxy_buffering_enabled"`
	ProxyBuffers             string `json:"proxy_buffers"`
	ProxyBufferSize          string `json:"proxy_buffer_size"`
	ProxyBusyBuffersSize     string `json:"proxy_busy_buffers_size"`
	GzipEnabled              bool   `json:"gzip_enabled"`
	GzipMinLength            int    `json:"gzip_min_length"`
	GzipCompLevel            int    `json:"gzip_comp_level"`
	Resolvers                string `json:"resolvers,omitempty"`
	CacheEnabled             bool   `json:"cache_enabled"`
	CachePath                string `json:"cache_path,omitempty"`
	CacheLevels              string `json:"cache_levels"`
	CacheInactive            string `json:"cache_inactive"`
	CacheMaxSize             string `json:"cache_max_size"`
	CacheKeyTemplate         string `json:"cache_key_template"`
	CacheLockEnabled         bool   `json:"cache_lock_enabled"`
	CacheLockTimeout         string `json:"cache_lock_timeout"`
	CacheUseStale            string `json:"cache_use_stale"`
	MainConfigTemplate       string `json:"main_config_template,omitempty"`
}

type Document struct {
	Routes          []Route        `json:"routes"`
	OpenRestyConfig ConfigSnapshot `json:"openresty_config"`
	WAF             WAFDocument    `json:"waf"`
}

type Result struct {
	MainConfig   string
	RouteConfig  string
	SupportFiles []SupportFile
	Checksum     string
}

type routeCacheConfig struct {
	Enabled bool
	Policy  string
	Rules   []string
}

type routeLimitConfig struct {
	LimitConnPerServer int
	LimitConnPerIP     int
	LimitRate          string
}

type routeUpstreamConfig struct {
	Name              string
	Scheme            string
	ProxyPassURI      string
	Servers           []string
	UsesNamedUpstream bool
}

var requiredMainConfigTemplatePlaceholders = []string{
	"{{OpenRestyWorkerProcesses}}",
	"{{OpenRestyWorkerConnections}}",
	"{{OpenRestyWorkerRlimitNofile}}",
	"{{OpenRestyConnectionUpgradeMap}}",
	"{{OpenRestyDefaultServerBlock}}",
	"{{OpenRestyAccessLogPath}}",
	"{{OpenRestyEventsUseDirective}}",
	"{{OpenRestyEventsMultiAcceptDirective}}",
	"{{OpenRestyKeepaliveTimeout}}",
	"{{OpenRestyKeepaliveRequests}}",
	"{{OpenRestyClientHeaderTimeout}}",
	"{{OpenRestyClientBodyTimeout}}",
	"{{OpenRestyClientMaxBodySize}}",
	"{{OpenRestyLargeClientHeaderBuffers}}",
	"{{OpenRestySendTimeout}}",
	"{{OpenRestyProxyConnectTimeout}}",
	"{{OpenRestyProxySendTimeout}}",
	"{{OpenRestyProxyReadTimeout}}",
	"{{OpenRestyProxyRequestBuffering}}",
	"{{OpenRestyProxyBuffering}}",
	"{{OpenRestyProxyBuffers}}",
	"{{OpenRestyProxyBufferSize}}",
	"{{OpenRestyProxyBusyBuffersSize}}",
	"{{OpenRestyGzip}}",
	"{{OpenRestyGzipMinLength}}",
	"{{OpenRestyGzipCompLevel}}",
	"{{OpenRestyCacheBlock}}",
	"{{OpenRestyRouteConfigInclude}}",
}
